Drop random items on elite mob death: true
Mob level to item rank multiplier: 0.5
Monitor randomly generated drops on console: false
Percentage (%) of times random item drop instead of custom loot: 20
Valid material list for random items:
- DIAMOND_SWORD
- GOLD_SWORD
- IRON_SWORD
- STONE_SWORD
- WOOD_SWORD
- BOW
- DIAMOND_PICKAXE
- GOLD_PICKAXE
- IRON_PICKAXE
- STONE_PICKAXE
- WOOD_PICKAXE
- DIAMOND_SPADE
- GOLD_SPADE
- IRON_SPADE
- STONE_SPADE
- WOOD_SPADE
- DIAMOND_HOE
- GOLD_HOE
- IRON_HOE
- STONE_HOE
- WOOD_HOE
- DIAMOND_AXE
- GOLD_AXE
- IRON_AXE
- STONE_AXE
- WOOD_AXE
- SHEARS
- SHIELD
- FISHING_ROD
- CHAINMAIL_HELMET
- DIAMOND_HELMET
- GOLD_HELMET
- IRON_HELMET
- LEATHER_HELMET
- CHAINMAIL_CHESTPLATE
- DIAMOND_CHESTPLATE
- GOLD_CHESTPLATE
- IRON_CHESTPLATE
- LEATHER_CHESTPLATE
- CHAINMAIL_LEGGINGS
- DIAMOND_LEGGINGS
- GOLD_LEGGINGS
- IRON_LEGGINGS
- LEATHER_LEGGINGS
- CHAINMAIL_BOOTS
- DIAMOND_BOOTS
- GOLD_BOOTS
- IRON_BOOTS
- LEATHER_BOOTS
Valid Enchantments:
  ARROW_DAMAGE:
    Allow: true
    Max Level: 10
  ARROW_FIRE:
    Allow: true
    Max Level: 10
  ARROW_INFINITE:
    Allow: true
  ARROW_KNOCKBACK:
    Allow: true
    Max Level: 10
  BINDING_CURSE:
    Allow: true
  DAMAGE_ALL:
    Allow: true
    Max Level: 10
  DAMAGE_ARTHROPODS:
    Allow: true
    Max Level: 10
  DAMAGE_UNDEAD:
    Allow: true
    Max Level: 10
  DEPTH_STRIDER:
    Allow: true
    Max Level: 10
  DIG_SPEED:
    Allow: true
    Max Level: 10
  DURABILITY:
    Allow: true
    Max Level: 10
  FIRE_ASPECT:
    Allow: true
    Max Level: 10
  FROST_WALKER:
    Allow: true
    Max Level: 10
  KNOCKBACK:
    Allow: true
    Max Level: 10
  LOOT_BONUS_BLOCKS:
    Allow: true
    Max Level: 10
  LOOT_BONUS_MOBS:
    Allow: true
    Max Level: 10
  LUCK:
    Allow: true
    Max Level: 10
  LURE:
    Allow: true
    Max Level: 10
  MENDING:
    Allow: false
  OXYGEN:
    Allow: true
    Max Level: 10
  PROTECTION_ENVIRONMENTAL:
    Allow: true
    Max Level: 10
  PROTECTION_EXPLOSIONS:
    Allow: true
    Max Level: 10
  PROTECTION_FALL:
    Allow: true
    Max Level: 10
  PROTECTION_FIRE:
    Allow: true
    Max Level: 10
  PROTECTION_PROJECTILE:
    Allow: true
    Max Level: 10
  SILK_TOUCH:
    Allow: true
  SWEEPING_EDGE:
    Allow: true
    Max Level: 10
  THORNS:
    Allow: true
    Max Level: 10
  VANISHING_CURSE:
    Allow: true
  WATER_WORKER:
    Allow: true
    Max Level: 10
Material name:
  Sword: Sword
  Bow: Bow
  Pickaxe: Pickaxe
  Spade: Spade
  Hoe: Hoe
  Axe: Axe
  Helmet: Helmet
  Chestplate: Chestplate
  Leggings: Leggings
  Boots: Boots
  Fishing Rod: Fishing Rod
  Shield: Shield
  Shears: Shears
Valid nouns:
- MagmaGuy
- Dawn
- Sunset
- Heaven
- Hell
- Angel
- Archangel
- Cherub
- Seraph
- Demon
- Fiend
- Bat
- Chicken
- Cow
- Mooshroom
- Pig
- Rabbit
- Sheep
- Squid
- Villager
- Cave Spider
- Enderman
- Polar Bear
- Spider
- Zombie Pigman
- Blaze
- Creeper
- Elder Guardian
- Endermite
- Evoker
- Ghast
- Guardian
- Husk
- Magma Cube
- Shulker
- Silverfish
- Skeleton
- Slime
- Stray
- Vex
- Vindicator
- Witch
- Wither Skeleton
- Zombie
- Donkey
- Horse
- Llama
- Mule
- Ocelot
- Wolf
- Iron Golem
- Snow Golem
- Ender Dragon
- Wither
- Illusioner
- Parrot
- Giant
- Killer Bunny
- Steve
- Wolfbane
- Chaos
- Aeon
- Dragon
- Sphynx
- Minotaur
- Hades
- Oath
- Oathbreaker
- Deserter
- Betrayer
- Jade
- Light
- Darkness
- Oblivion
- Shadow
- Void
- Xeno
- Zealot
- Zenith
- Dusk
- Twilight
- Mob
- Elite  Mob
- Urist
- Dwarf
- Elf
- Ork
- Goblin
- Gnome
- Goliath
- Drow
- Human
- Halfling
- Half-Orc
- Beholder
- Mind Flayer
- Owlbear
- Bulette
- Rust Monster
- Hill Giant
- Stone Giant
- Frost Giant
- Fire Giant
- Cloud Giant
- Storm Giant
- Kobold
- Lich
- Ork
- Umber Hulk
- Fighter
- Wizard
- Paladin
- Cleric
- Ranger
- Archer
- Mage
- Tiefling
- Werewolf
- Vampire
- Centaur
- Catfolk
- Half-Giant
- Ogre
- Troll
- Rogue
- Barbarian
- Bard
- Druid
- Monk
- Sorcerer
- Warlock
- Demon Hunter
- Death Knight
- Priest
- Shaman
- Warrior
- Basilisk
- Chimera
- Imp
- Dryad
- Gargoyle
- Djinni
- Efreeti
- Ghost
- Hobgoblin
- Hydra
- Kraken
- Lamia
- Medusa
- Mimic
- Mummy
- Pegasus
- Roc
- Satyr
- Tarrasque
- Abomination
- Ghoul
- Treant
- Unicorn
- Wraith
- Acolyte
- Gladiator
- Knight
- Gryphon
- Raider
- Scout
- Spy
- Thg
- Noble
- Guard
- Veteran
- Wyvern
- Abyssal
- Infernal
- Elemental
- Tauren
- Pandaren
- Sasquatch
- Forsaken
- Yeti
- Banshee
- Arachnid
- Undead
- Night Elf
- Blood Elf
- Draenei
- Worgen
- Warlord
- Witch
- Magi
- Sage
- Thief
- Assassin
- Templar
- Beastmaster
- Berserker
- Inventor
- Luchador
- Pirate
- Vanguard
- Voidblade
- Whisp
- Peasant
- Footman
- Swordsman
- Thrall
- Felhound
- Huntress
- Hunter
Valid verb-er (noun):
- World Breaker
- World Shatterer
- Avenger
- Ashbringer
- Windseeker
- Defiler
- Thunderfury
- Slicer
- Slasher
- Cutter
- Stabber
- Scratcher
- Killer
- Slayer
- Destroyer
- Hugger
- Murderer
- Slapper
- Traveller
- Teleporter
- Blinker
- Wrecker
- Materializer
- Spawner
- Demander
- Assaulter
- Striker
- Ambusher
- Rusher
- Stormer
- Bombarder
- Barrager
- Smiter
- Charger
- Battler
- Hammerer
- Beater
- Combater
- Overwhelmer
- Raider
- Tackler
- Shooter
- Venturer
- Cracker
- Smasher
- Shatterer
- Fracturer
- Splinterer
- Pulverizer
- Tearer
- Renderer
- Snapper
- Burster
- Exploder
- Damager
- Fragmenter
- Splitter
- Fortifier
- Nudger
- Tapper
- Thumper
- Butter
- Clatterer
- Striker
- Whacker
- Slammer
- Summoner
- Screamer
- Shifter
- Transformer
- Modifyer
- Twister
- Blurrer
- Warper
- Alterer
- Adapter
- Evolver
- Hunter
- Trailer
- Follower
- Stalker
- Shadower
- Hounder
- Caser
- Mounter
- Ascender
- Riser
- Springer
- Hoarder
- Reaper
- Harvester
- Saver
- Shelterer
- Cloaker
- Shrouder
- Encloser
- Hider
- Masker
- Buryer
- Clouder
- Shader
- Sealer
- Enveloper
- Veiler
- Traverser
- Forder
- Glider
- Howler
- Whimperer
- Screamer
- Squealer
- Bawler
- Screecher
- Chopper
- Chipper
- Snipper
- Splitter
- Axer
- Slasher
- Renderer
- Tearer
- Thinner
- Cropper
- Carver
- Hacker
- Piercer
- Sawer
- Shaver
- Shearer
- Miner
- Excavater
- Burrower
- Driller
- Tunneler
- Invader
- Boarder
- Wanderer
- Intruder
- Evader
- Runner
- Dodger
- Crasher
- Battler
- Wrestler
- Scuffler
- Dueler
- Brawler
- Clasher
- Grappler
- Scrapper
- Attacker
- Feuder
- Catcher
- Solver
- Revealer
- Leaper
- Bouncer
- Vaulter
- Hopper
- Surger
- Punter
- Dropkicker
- Perceiver
- Fader
- Bleeder
- Weakener
- Forger
- Releaser
- Gatherer
- Crusher
- Propeller
- Jogger
- Sprinter
- Scouter
- Explorer
- Digger
- Trembler
- Parter
- Hacker
- Carver
- Divider
- Halver
- Breaker
- Renderer
- Ripper
- Grazer
- Imprisoner
- Cornerer
- Pinner
- Catcher
- Restrainer
- Binder
- Snagger
- Snatcher
- Cager
- Capturer
- Haunter
- Creeper
- Sneaker
Valid adjectives:
- Adorable
- Beautiful
- Clean
- Elegant
- Fancy
- Glamorous
- Handsome
- Long
- Magnificent
- Plain
- Quaint
- Sparkling
- Ugliest
- Red
- Orange
- Yellow
- Green
- Blue
- Purple
- Gray
- Black
- White
- Dead
- Odd
- Powerful
- Rich
- Vast
- Zealous
- Deafening
- Faint
- Melodic
- Quiet
- Thundering
- Whispering
- Hissing
- Ancient
- Fast
- Old
- Rapid
- Slow
- Rotten
- Creepy
- Crooked
- Empty
- Heavy
- Abhorrent
- Abnormal
- Absurd
- Acceptable
- Accidental
- Adamant
- Adventurous
- Agonizing
- Alert
- Annoyed
- Annoying
- Anxious
- Aromatic
- Aggressive
- Aloof
- Amazing
- Ambiguous
- Ambitious
- Amused
- Angry
- Arrogant
- Ashamed
- Aspiring
- Astonishing
- Auspicious
- Average
- Awesome
- Awful
- Bad
- Barbarous
- Bashful
- Beffiting
- Belligerent
- Beneficial
- Berserk
- Best
- Bewildered
- Big
- Bitter
- Bizarre
- Bloody
- Boiling
- Boundless
- Brash
- Brave
- Brawny
- Breakable
- Brief
- Bright
- Broken
- Busy
- Calculating
- Callous
- Calm
- Capricious
- Careful
- Careless
- Caring
- Cautious
- Ceaseless
- Certain
- Charming
- Cheap
- Chief
- Chilly
- Chivalrous
- Chunky
- Clear
- Clever
- Cloistered
- Clumsy
- Cloudy
- Classy
- Colossal
- Combative
- Common
- Confused
- Condemned
- Cool
- Courageous
- Cowardly
- Crazy
- Craven
- Cruel
- Cuddly
- Curious
- Cute
- Damaged
- Damaging
- Dangerous
- Dark
- Dashing
- Decisive
- Deep
- Defeated
- Defective
- Defiant
- Delicate
- Delicious
- Delightful
- Demonic
- Delirious
- Deranged
- Descriptive
- Devilish
- Difficult
- Diligent
- Direful
- Dirty
- Disastrous
- Disgusted
- Disgusting
- Disillusioned
- Distinct
- Disturbed
- Draconian
- Dramatic
- Dreary
- Dysfunctional
- Eager
- Elderly
- Electric
- Elite
- Enchanted
- Enchanting
- Energetic
- Enormous
- Entertaining
- Enthusiastic
- Envious
- Erratic
- Ethereal
- Evasive
- Excellent
- Excited
- Exciting
- Exotic
- Exuberant
- Fabulous
- Faded
- Fair
- Faithful
- 'False'
- Familiar
- Famous
- Fanatical
- Fantastic
- Fascinated
- Fat
- Fearful
- Fearless
- Feeble
- Festive
- Fierce
- Filthy
- Fine
- Finicky
- First
- Fixed
- Flashy
- Flawless
- Flimsy
- Flippant
- Flowery
- Fluffy
- Fluttering
- Foamy
- Foolish
- Forgetful
- Fortunate
- Frail
- Fragile
- Frantic
- Free
- Freezing
- Fresh
- Friendly
- Frightening
- Fumbling
- Funny
- Furry
- Furtive
- Fuzzy
- Giant
- Gifted
- Gigantic
- Glistening
- Glorious
- Godly
- Good
- Goofy
- Gorgeous
- Graceful
- Grandiose
- Grateful
- Greasy
- Great
- Greedy
- Grieving
- Groovy
- Grotesque
- Grubby
- Gruesome
- Grumpy
- Guarded
- Guiltless
- Gullible
- Gutsy
- Guttural
- Hallowed
- Hanging
- Hapless
- Happy
- Harmonious
- Hateful
- Healthy
- Heartbreaking
- Heavenly
- Hellish
- Helpful
- Helpless
- Hesitant
- Hideous
- Hilarious
- Hollow
- Homeless
- Honorable
- Horrible
- Hospitable
- Huge
- Hulking
- Humorous
- Hungry
- Hurt
- Hushed
- Hypnotic
- Hysterical
- Icky
- Icy
- Ignorant
- Ill
- Illegal
- Illustrious
- Imaginary
- Immense
- Imminent
- Impartial
- Imperfect
- Impolite
- Important
- Incandescent
- Incompetent
- Industrious
- Incredible
- Inexpensive
- Infamous
- Innocent
- Inquisitive
- Insidious
- Instinctive
- Intelligent
- Interesting
- Invincible
- Irate
- Itchy
- Jaded
- Jagged
- Jealous
- Jolly
- Joyous
- Jumpy
- Juvenile
- Keen
- Kind
- Kindhearted
- Knowing
- Knowledgeable
- Known
- Labored
- Lame
- Large
- Last
- Late
- Laughable
- Lazy
- Lean
- Lethal
- Light
- Little
- Living
- Lonely
- Loud
- Lovely
- Lucky
- Magenta
- Magical
- Majestic
- Malicious
- Marked
- Massive
- Marvelous
- Mean
- Medical
- Melted
- Messy
- Mighty
- Military
- Mindless
- Minor
- Misty
- Mixed
- Modern
- Motionless
- Mysterious
- Naive
- Narrow
- Natural
- Neat
- Necessary
- Needless
- Needy
- Nervous
- New
- Nice
- Normal
- Nostalgic
- Numberless
- Obsolete
- Obtainable
- Oceanic
- Old-fashioned
- Omniscient
- Optimal
- Ordinary
- Organic
- Outstanding
- Oval
- Overrated
- Painful
- Parallel
- Pathetic
- Peaceful
- Penitent
- Perfect
- Periodic
- Petite
- Physical
- Pink
- Plastic
- Pleasant
- Pointless
- Polite
- Poor
- Precious
- Premium
- Present
- Pretty
- Private
- Productive
- Protective
- Public
- Puzzling
- Questionable
- Quick
- Quickest
- Rare
- Ready
- Real
- Rebel
- Regular
- Remarkable
- Responsible
- Romantic
- Round
- Royal
- Sad
- Safe
- Salty
- Satisfying
- Scared
- Scary
- Scientific
- Scrawny
- Screeching
- Second
- Second-hand
- Secret
- Selfish
- Sequacious
- Serious
- Shallow
- Sharp
- Shiny
- Shocking
- Short
- Shy
- Sick
- Silent
- Silky
- Silly
- Simple
- Skinny
- Slim
- Slimy
- Slippery
- Small
- Smart
- Smiling
- Smooth
- Sneaky
- Soft
- Solid
- Special
- Spectacular
- Spicy
- Spiky
- Splendid
- Spooky
- Spotless
- Square
- Staking
- Standing
- Steady
- Sticky
- Strange
- Striped
- Strong
- Successful
- Super
- Supreme
- Sweet
- Talented
- Tall
- Tasty
- Temporary
- Tense
- Terrible
- Terrific
- Tested
- Thankful
- Thick
- Thin
- Thirsty
- Thoughtful
- Tiny
- Tired
- Tricky
- Troubled
- 'True'
- Ugly
- Ultra
- Unadvised
- Unarmed
- Uncovered
- Unhealthy
- Unique
- Unknown
- Unnatural
- Unused
- Unusual
- Used
- Useful
- Useless
- Valuable
- Violent
- Waiting
- Wandering
- Warm
- Weak
- Wealthy
- Whole
- Wise
- Wonderful
- Wooden
- Worried
- Worthless
- Wrong
- Menacing
Valid verbs:
- Slashing
- Cutting
- Stabbing
- Scratching
- Killing
- Slaying
- Butchering
- Destroying
- Tickling
- Hugging
- Murdering
- Slapping
- Hissing
- Traveling
- Teleporting
- Blinking
- Destroying
- Wrecking
- Flashing
- Materializing
- Spawning
- Questioning
- Inquiring
- Pleading
- Demanding
- Interrogating
- Querying
- Assaulting
- Striking
- Ambushing
- Assailing
- Rushing
- Storming
- Bombarding
- Barraging
- Smiting
- Charging
- Clobbering
- Battling
- Battering
- Hammering
- Beating
- Combating
- Overwhelming
- Raiding
- Tackling
- Shooting
- Venturing
- Cracking
- Rupturing
- Smashing
- Shattering
- Fracturing
- Splintering
- Pulverizing
- Tearing
- Rending
- Snapping
- Bursting
- Exploding
- Damaging
- Fragmenting
- Splitting
- Fortifying
- Nudging
- Tapping
- Jostling
- Thumping
- Butting
- Clattering
- Striking
- Whacking
- Slamming
- Summoning
- Screaming
- Bellowing
- Roaring
- Shifting
- Transforming
- Modifying
- Twisting
- Mutating
- Distorting
- Blurring
- Adjusting
- Warping
- Altering
- Adapting
- Evolving
- Varying
- Hunting
- Trailing
- Following
- Stalking
- Shadowing
- Hounding
- Casing
- Mounting
- Ascending
- Rising
- Heaving
- Springing
- Cresting
- Gathering
- Corralling
- Hoarding
- Reaping
- Harvesting
- Saving
- Sheltering
- Cloaking
- Shrouding
- Enclosing
- Concealing
- Hiding
- Disguising
- Masking
- Burying
- Smothering
- Clouding
- Shielding
- Shading
- Sealing
- Enveloping
- Veiling
- Obscuring
- Traversing
- Fording
- Gliding
- Howling
- Whimpering
- Screaming
- Shrieking
- Squealing
- Roaring
- Wailing
- Bawling
- Screeching
- Cleaving
- Chopping
- Chipping
- Severing
- Slicing
- Snipping
- Splitting
- Axing
- Slashing
- Rending
- Tearing
- Thinning
- Cropping
- Carving
- Dissecting
- Hacking
- Piercing
- Sawing
- Shaving
- Shearing
- Mining
- Delving
- Excavating
- Burrowing
- Drilling
- Hollowing
- Gouging
- Tunneling
- Invading
- Boarding
- Wandering
- Infiltrating
- Intruding
- Evading
- Fleeing
- Running
- Dodging
- Crashing
- Battling
- Tussling
- Wrestling
- Scuffling
- Dueling
- Brawling
- Jousting
- Sparring
- Clashing
- Warring
- Grappling
- Scrapping
- Attacking
- Feuding
- Skirmishing
- Discovering
- Detecting
- Catching
- Solving
- Revealing
- Unearthing
- Leaping
- Bouncing
- Springing
- Vaulting
- Hopping
- Surging
- Punting
- Booting
- Dropkicking
- Sensing
- Perceiving
- Detecting
- Fading
- Bleeding
- Shrinking
- Weakening
- Abating
- Diminishing
- Forging
- Releasing
- Gathering
- Collecting
- Culling
- Crushing
- Propelling
- Jogging
- Sprinting
- Questing
- Scouting
- Exploring
- Digging
- Trembling
- Rattling
- Parting
- Hacking
- Rupturing
- Carving
- Dividing
- Halving
- Breaking
- Sundering
- Separating
- Rending
- Ripping
- Grazing
- Imprisoning
- Snaring
- Cornering
- Entangling
- Pinning
- Catching
- Restraining
- Binding
- Hooking
- Snagging
- Snatching
- Caging
- Capturing
- Haunting
- Creeping
- Sneaking
- Spying
- Avenging
